// JWT sign / verify.
//
// OWASP A02 + A07 — RS256 asymmetric, 4096-bit RSA keys generated by
// infra/scripts/generate-secrets.sh. Algorithm is pinned to RS256 on verify
// so a forged token using HS256 (and the public key as the "secret") cannot
// pass — a well-known JWT pitfall.

import fs from 'node:fs';
import jwt from 'jsonwebtoken';
import { loadEnv } from '../config/env';

const ISSUER = 'backend';
const AUDIENCE = 'mobile-clients';

export interface JwtClaims {
  sub: string;       // userId — opaque UUID (OWASP A01)
  role: string;
  iat?: number;
  exp?: number;
  iss?: string;
  aud?: string;
}

let cachedPriv: Buffer | undefined;
let cachedPub: Buffer | undefined;

function keys(): { priv: Buffer; pub: Buffer } {
  if (!cachedPriv || !cachedPub) {
    const env = loadEnv();
    cachedPriv = fs.readFileSync(env.JWT_PRIVATE_KEY_PATH);
    cachedPub = fs.readFileSync(env.JWT_PUBLIC_KEY_PATH);
  }
  return { priv: cachedPriv, pub: cachedPub };
}

export function signAccessToken(input: { userId: string; role: string }): string {
  const env = loadEnv();
  const { priv } = keys();
  return jwt.sign(
    { sub: input.userId, role: input.role },
    priv,
    {
      algorithm: 'RS256',
      expiresIn: env.JWT_ACCESS_EXPIRY,
      issuer: ISSUER,
      audience: AUDIENCE,
    },
  );
}

export function verifyAccessToken(token: string): JwtClaims {
  const { pub } = keys();
  return jwt.verify(token, pub, {
    algorithms: ['RS256'],
    issuer: ISSUER,
    audience: AUDIENCE,
  }) as JwtClaims;
}

export function __resetJwtKeysForTests(): void {
  cachedPriv = undefined;
  cachedPub = undefined;
}
